### PR TITLE
fix(iOS): convert HEIC/HEIF photos to PNG/JPEG

### PR DESCRIPTION
**Pull request by FdezRomero**
Related to https://github.com/terikon/cordova-plugin-photo-library/issues/105

### CODE REVIEW

**Comment by AndreasGassmann** [comment]
Hey, thanks for the PR!

**Comment by AndreasGassmann** [comment]
If you have time, would you mind joining https://gitter.im/cordova-plugin-photo-library/Lobby so we can have a chat sometime? I'm curious how you use the plugin and what your plans are with it. I have some ideas for improvements, but never got around to implementing them.

**Comment by FdezRomero** [comment]
No problem! Thank you for the native file URLs.

It's 2 a.m. here, but I joined the Gitter room so let's have a chat tomorrow.

**Comment by AndreasGassmann** [comment]
Same here, see you another day ;).

**Pull request merged**
